from pathlib import Path
from playwright.sync_api import sync_playwright
import json, re

with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=r'C:\Program Files\Google\Chrome\Application\chrome.exe',headless=True)
 page=browser.new_page(viewport={'width':390,'height':844},device_scale_factor=1)
 errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:8080',wait_until='domcontentloaded')
 page.locator('flt-glass-pane').wait_for(timeout=60000,state='attached')
 page.wait_for_timeout(950)
 page.screenshot(path='previews/launch-mobile.png')
 page.wait_for_timeout(2200)
 placeholder=page.locator('flt-semantics-placeholder')
 if placeholder.count():placeholder.evaluate('(e)=>e.click()')
 page.get_by_role('button',name='Sign in',exact=True).wait_for()
 page.screenshot(path='previews/welcome-mobile.png')
 page.get_by_role('button',name='Sign in',exact=True).click()
 page.wait_for_timeout(400)
 page.screenshot(path='previews/login-mobile.png')
 page.get_by_role('button',name='Close sign-in',exact=True).click()
 page.get_by_role('button',name='Create account',exact=True).click()
 page.wait_for_timeout(400)
 page.screenshot(path='previews/signup-mobile.png')
 page.get_by_role('button',name='Preview new-user onboarding',exact=True).click()
 page.wait_for_timeout(500)
 page.screenshot(path='previews/onboarding-mobile.png')
 page.set_viewport_size({'width':1440,'height':1000})
 page.wait_for_timeout(500)
 page.screenshot(path='previews/onboarding-desktop.png')
 page.set_viewport_size({'width':390,'height':844})
 page.get_by_role('button',name='Skip tour',exact=True).click()
 page.wait_for_timeout(600)
 page.screenshot(path='previews/catalog-mobile.png')
 page.mouse.move(200,500);page.mouse.wheel(0,450);page.wait_for_timeout(400)
 page.screenshot(path='previews/products-mobile.png')
 page.get_by_role('button',name=re.compile('Add Hass Avocados')).click()
 page.mouse.move(5,5);page.wait_for_timeout(400)
 page.screenshot(path='previews/product-added-mobile.png')
 page.get_by_role('button',name=re.compile('View bag')).click()
 page.wait_for_timeout(400)
 page.screenshot(path='previews/bag-mobile.png')
 page.get_by_role('button',name='Continue to checkout',exact=True).click()
 page.wait_for_timeout(400)
 page.screenshot(path='previews/checkout-mobile.png')
 for label,value in [('Full name','Demo Customer'),('Mobile number','9876543210'),('Flat, building and street','10 Demo Street'),('City','Bengaluru'),('PIN code','560001')]:
  page.get_by_role('textbox',name=re.compile(label)).fill(value)
 page.get_by_role('button',name='Place demo order',exact=True).click()
 page.wait_for_timeout(400)
 page.screenshot(path='previews/order-confirmation-mobile.png')
 page.get_by_role('button',name='View my orders',exact=True).click()
 page.wait_for_timeout(400)
 page.screenshot(path='previews/orders-mobile.png')
 print('Saved updated launch, authentication, onboarding, shopping, and order screenshots.')
 assert not errors,errors
 print('BROWSER_ERRORS',json.dumps(errors))
 browser.close()
